{% set name = "egglog" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/egglog-{{ version }}.tar.gz
  sha256: 87e086c66e6ace2ca2186547a72e48c9288ee9bf5ae90c9647a2d9cf4bdb81b1

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    # Try loosening maturin requirement for python 3.12
    - python
    - maturin >=0.13 #,<0.14
    - pip
  run:
    - python
    - typing-extensions
    - black
    - python-graphviz

    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - egglog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/metadsl/egglog-python
  doc_url: https://egg-smol-python.readthedocs.io
  summary: E-graphs in Python built around the the egglog rust library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
