{% set name = "egglog" %}
{% set version = "11.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/egglog-{{ version }}.tar.gz
  sha256: 5672d8bd9b8e7aec9a3c67e2d826dbe52636a04608d39f93ba00862b1ac58417

build:
  skip: true  # [py<311 or py>=313]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=1.7,<2.0
    - pip
  run:
    - python
    - typing-extensions
    - black
    - python-graphviz
    - anywidget

test:
  imports:
    - egglog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/metadsl/egglog-python
  doc_url: https://egg-smol-python.readthedocs.io
  summary: E-graphs in Python built around the the egglog rust library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
