{% set name = "egglog" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/egglog-{{ version }}.tar.gz
  sha256: f41b41d2e6081bbe30749234c44357b0be29f79e7387b5104a4a2e86737be787

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=0.13,<0.14
    - pip
  run:
    - python
    - typing-extensions
    - black
    - python-graphviz

test:
  imports:
    - egglog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/metadsl/egglog-python
  doc_url: https://egg-smol-python.readthedocs.io
  summary: E-graphs in Python built around the the egglog rust library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
