{% set name = "egglog" %}
{% set version = "7.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/egglog-{{ version }}.tar.gz
  sha256: 2cc940418b054c25d6e2918bd32dafa0d887061a89a767e1484b94410ce0254a

build:
  # Unavailable for 3.12 until upstream move to a newer version of maturin
  skip: true  # [py<310 or py>=312]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=0.13,<0.14
    - pip
  run:
    - python
    - typing-extensions
    - black
    - python-graphviz

test:
  imports:
    - egglog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/metadsl/egglog-python
  doc_url: https://egg-smol-python.readthedocs.io
  summary: E-graphs in Python built around the the egglog rust library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
